---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner-deployment
  labels:
    app: nginx
  annotations:
    owner: "owner1"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        owner: "owner1"
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80